name: Java CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean verify

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            target/*.jar
            target/site/apidocs/**